extends Label

var dead = false
const deathMessages = ["[YOU DIED]", 
"[YOU BECAME A DRONE]", 
"[YOU WERE INFLUENCED]", 
"[YOU SUCCUMBED TO PREDATORY BUSINESS PRACTICES.]",
"[YOU WERE ACQUIRED BY MICROSOFT]",
"[YOUR RESOURCES WERE REFINED]",
"[YOU WERE CENSORED]",
"[YOU ADVOCATED AGAINST GUN SAFETY]",
"[YOU STOOD IN THE WAY OF PROGRESS]",
"[YOU BECAME A TECH BRO]",
"[YOU BET TOO HARD ON BITCOIN]",
"[YOU GOT SANCTIONED]",
"[YOU WERE SENT TO ARBITRATION]",
"[YOU DIDN'T READ THE FINE PRINT]",
"[YOUR LIFE WAS THE COMPANY'S TO TAKE]",
"[DISNEY ENDED YOUR LIFE SUBSCRIPTION]",
"[YOUR FREE TRIAL OF LIFE ENDED]",
"[COSTCO MADE THEIR HOTDOGS $1.51]"]

func _on_hud_died() -> void:
	text = deathMessages.pick_random()
